function [tipo,lb] = loglambdafig(X1,Y1,M,home_fig,nx,ny,nz,...
    eta1,eta2,eta3,beta,nu,ntipo,nome)
    if(ntipo==2)
        tipo=[home_fig nome 'autoval'];
        a = num2str(beta,'%5.1f');
        i = find(a == '.'); a = [a(1:i-1) '-' a(i+1:end)];
        i = find(a == '-'); if a(i+1) == '0', a = a(1:i-1); end
        b = [];
        c = [];
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if(ntipo==1)
        tipo=[home_fig nome 'autoval'];
        a = num2str(eta1,'%5.1f');
        b = num2str(eta2,'%5.1f');
        c = num2str(eta3,'%5.1f');
        i = find(a == '.'); a = [a(1:i-1) '-' a(i+1:end)];
        i = find(a == '-'); if a(i+1) == '0', a = a(1:i-1); end
        i = find(b == '.'); b = [b(1:i-1) '-' b(i+1:end)];
        i = find(b == '-'); if b(i+1) == '0', b = b(1:i-1); end
        i = find(c == '.'); c = [c(1:i-1) '-' c(i+1:end)];
        i = find(c == '-'); if c(i+1) == '0', c = c(1:i-1); end
     end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if(ntipo==3)
        tipo=[home_fig nome 'autoval'];
        a = num2str(eta1,'%5.1f');
        b = num2str(eta2,'%5.1f');
        c = num2str(eta3,'%5.1f');
        i = find(a == '.'); a = [a(1:i-1) '-' a(i+1:end)];
        i = find(a == '-'); if a(i+1) == '0', a = a(1:i-1); end
        i = find(b == '.'); b = [b(1:i-1) '-' b(i+1:end)];
        i = find(b == '-'); if b(i+1) == '0', b = b(1:i-1); end
        i = find(c == '.'); c = [c(1:i-1) '-' c(i+1:end)];
        i = find(c == '-'); if c(i+1) == '0', c = c(1:i-1); end
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if(ntipo==4)
        tipo=[home_fig nome 'autoval'];
        a = num2str(nu,'%5.1f');
        i = find(a == '.'); a = [a(1:i-1) '-' a(i+1:end)];
        i = find(a == '-'); if a(i+1) == '0', a = a(1:i-1); end
        b = [];
        c = [];
    end
    if nz == 1
        if ntipo == 2
            lb = ['beta' a]
        else
            if ntipo == 4
                lb = ['nu' a]
            else
                lb = [a 'x' b];
            end
        end
    else
        if ntipo == 2
            lb = ['beta' a]
        else
            if ntipo == 4
                lb = ['nu' a]
            else
                lb = [a 'x' b 'x' c];
            end
        end
    end
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Nov-2010 18:21:29
A = 0*min(X1);
B = max(X1);
C = min(Y1);
D = max(Y1);
C = 1.0e-12;
D = 1.001e+04;
aspec = 0.5 * (B - A) / (D - C);

% Create figure
figure1 = figure(36);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',18,'FontName','Times New Roman');

% Create plot
semilogy(X1(1:M),Y1(1:M),'MarkerFaceColor','none','Marker','none',...
    'MarkerSize',8,'LineWidth',5,...
    'Color',[0.0 0.45 0.74]);
hold on
% Create plot
semilogy(X1(M+1:end),Y1(M+1:end),'MarkerFaceColor','none','Marker','none',...
    'MarkerSize',8,'LineWidth',5,...
    'Color',[0.929411764705882 0.694117647058824 0.125490196078431]);

% Create xlabel
xlabel('$\mathsf{M}$','Interpreter','latex','FontSize',22,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('$\lambda$','Interpreter','latex','FontSize',22,...
    'FontName','Times New Roman');

xlim([A B]);
ylim([C D]);

aux = floor(B/5);
aux1= mod(aux,10);
dx  = aux - aux1;
x   = [A : dx : B];

% box(axes1,'on');
% hold(axes1,'off');
% Set the remaining axes properties
tck = [1.e-10 1.e-8 1.e-6 1e-4 1e-2 1 1e+2 1e4];
tck = [1e-12 1.e-8 1e-4 1 1e4];
set(axes1,'DataAspectRatio',[aspec 1 1],'FontSize',18,'TickDir','both',...
    'TickLabelInterpreter','latex','XMinorTick','on','YMinorTick','on',...
    'YTick',tck,'XTick',...
    x);
return

