function plot2Y(X1,Y1,Y2, xname, yname1, yname2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
A = min(X1); B = max(X1);
C1= min(min(Y1)); D1 = max(max(Y1));
C2= min(min(Y2)); D2 = max(max(Y2))*0+1;
C1=0.0; C2=0.0;
D1=1.0; D2=1.0;
asp1 = [(B-A)/(D1-C1) 1 1];
asp2 = [(B-A)/(D2-C2) 1 1];
%  Auto-generated by MATLAB on 19-Jan-2023 11:48:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
colororder([0.85 0.325 0.098]);

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create plot
plot(X1,Y1,'DisplayName','$\mu_\kappa$','LineWidth',4,...
    'Color',[0 0.447 0.741]);
xlim([A B]);
ylim([C1 D1]);

% Create ylabel
ylabel(yname1,'Interpreter','latex');

% Set the remaining axes properties
set(axes1,'YColor',[0 0.447 0.741],'YMinorTick','on',...
    'DataAspectRatio',asp1);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X1,Y2,'DisplayName','$\sigma_\kappa$','LineWidth',4,...
    'Color',[0.93 0.69 0.1255]);

% Create ylabel
ylabel(yname2,'FontSize',18,'Interpreter','latex',...
    'Color',[0.93 0.69 0.1255]);

% Set the remaining axes properties
set(axes1,'YColor',[0.93 0.69 0.1255],'YMinorTick','on',...
    'DataAspectRatio',asp2);
% Create xlabel
xlabel(xname,'FontSize',18,'Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');

xlim([A B]);
ylim([C2 D2]);

% Set the remaining axes properties
set(axes1,'FontSize',16,'TickDir','both','TickLabelInterpreter','latex',...
    'XMinorTick','on','DataAspectRatio',asp2);
% Create legend
% legend1 = legend(axes1,'show');
% set(legend1,'Location','northwest','Interpreter','latex','FontSize',14,...
%     'FontName','Times',...
%     'EdgeColor','none',...
%     'Color','none');
end

